# Generated by Django 4.1.2 on 2022-11-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_register',
            field=models.DateField(max_length=8),
        ),
    ]
